// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SpamDetector
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("likelySpam")]
        public bool LikelySpam { get; set; }

        [JsonProperty("isDisposableEmail")]
        public bool IsDisposableEmail { get; set; }

        [JsonProperty("isIPBlacklisted")]
        public bool IsIpBlacklisted { get; set; }

        [JsonProperty("ipDetails")]
        public IpDetails IpDetails { get; set; }

        [JsonProperty("parsed")]
        public bool Parsed { get; set; }
    }

    public partial class IpDetails
    {
        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }
    }
}
